### ISSUE TITLE
Version number in about screen does not reflect correct version

### ISSUE THREAD

**Issue by mthp1999** [lauralex/dwm_lut#10]
![image](https://user-images.githubusercontent.com/12549239/218345821-bef7f52d-6cc6-4fb9-8092-556c8034a72b.png)
![image](https://user-images.githubusercontent.com/12549239/218345827-8fdce2d6-e736-4afc-9bff-bd657fb3b1ff.png)
I have version 3.9.2 but the about section hasn't been updated to reflect that

**Comment by SxWolfxC** [comment]
i have the same problem.

**Comment by lauralex** [comment]
Yeah, forgot about that, I will fix it
