### ISSUE TITLE
Failed to load or initialize DLL.

### ISSUE THREAD

**Issue by Marti-Ferret** [lauralex/dwm_lut#11]
![image](https://user-images.githubusercontent.com/73919571/218471929-1f7339f9-dce9-4e8e-bb24-19ca1493b5f3.png)

**Comment by lauralex** [comment]
What version of windows are you using?

**Comment by Marti-Ferret** [comment]
![image](https://user-images.githubusercontent.com/73919571/218493687-fb42f087-e493-497e-a956-d9c216e5b5cc.png)

**Comment by lauralex** [comment]
Yeah, it's not updated. You should have 22H2

**Comment by Marti-Ferret** [comment]
Okey, Thank you.
