### ISSUE TITLE
windows defender identifies this program as a virus

### ISSUE THREAD

**Issue by activedecay** [lauralex/dwm_lut#14]
windows defender identifies this program as a virus, yo

after building the gui.exe and launching it, it was deleted by windows defender
![Screenshot 2023-02-14 104548](https://user-images.githubusercontent.com/4298390/218817065-01c2913a-4c1b-42b3-938b-564c43cc4479.png)

![Screenshot 2023-02-14 104611](https://user-images.githubusercontent.com/4298390/218817048-55ee3f98-e0df-43d7-97af-926e9d13a903.png)

this issues is a duplicate of 
https://github.com/ledoge/dwm_lut/issues/11

**Comment by lauralex** [comment]
> windows defender identifies this program as a virus, yo
> 
> after building the gui.exe and launching it, it was deleted by windows defender ![Screenshot 2023-02-14 104548](https://user-images.githubusercontent.com/4298390/218817065-01c2913a-4c1b-42b3-938b-564c43cc4479.png)
> 
> ![Screenshot 2023-02-14 104611](https://user-images.githubusercontent.com/4298390/218817048-55ee3f98-e0df-43d7-97af-926e9d13a903.png)
> 
> this issues is a duplicate of [ledoge#11](https://github.com/ledoge/dwm_lut/issues/11)

It's pretty normal. If you don't want the AV to flag the program, compile it yourself
