### ISSUE TITLE
Unable to run in network because of .exe run denied, .msi is needed

### ISSUE THREAD

**Issue by koraalex** [lauralex/dwm_lut#20]
Dear lauralex,

As you're successor in dwm_lut modification, I hope you can help me and compile an .msi package. There's difference between executable and application run for limited users. Moreover, task scheduler doesn't run dwm_lut with network admin rights, it produces error instead. I've tried different ways together with admins, but when .exe run is denied, automatic start of dwm_lut executable is impossible (it works as hand-run with admin credentials). I suppose, this happens cause of dwm_lut calls user's dwm process, but task scheduler provides admin's dwm in this case.

Could you help me?

I'm new on GitHub, so I'm sorry for possible wrong "request as issue" posting. You may know me as time-to-time DisplayCAL forum member. Great wishes, Alex

**Comment by lauralex** [comment]
I could look into it

**Comment by koraalex** [comment]
Thank you! I'll be glad to hear news in this thread.

**Comment by lauralex** [comment]
I uploaded a msi installer. Check if it's fine

**Comment by lauralex** [comment]
Closing this issue

**Comment by koraalex** [comment]
Great thanks! Sorry for late answer. I'll test this desirable feature some days later and give you a feedback.
