### ISSUE TITLE
When applying a LUT on Windows 11 there are too many debug messages

### ISSUE THREAD

**Issue by webs0r** [lauralex/dwm_lut#26]
Hi, thanks for this fantastic tool!
Is it possible to remove the debug messages when applying LUT on Windows 11?
For both when applying using the apply button as well as the command line -apply>

**Comment by lauralex** [comment]
@webs0r Hi, are you referring to the released binary, or the source code?

**Comment by webs0r** [comment]
The released binary - in the UI after clicking apply, or when running command line, there's a sequence of approx 4 message boxes that appear that I have to press OK on before the LUT gets applied.

**Comment by lauralex** [comment]
@webs0r Oh, I see, maybe I forgot to disable them

**Comment by lauralex** [comment]
@webs0r I updated the release artifacts, now there are no messages

**Comment by BiscuitCookies** [comment]
The debug boxes still appear on [v3.9.6](https://github.com/lauralex/dwm_lut/releases/tag/v3.9.6)

**Comment by NightHammer1000** [comment]
Yep. Still here

**Comment by antonmeleshkevich** [comment]
Confirm. All the messages are still there.
@lauralex
