### ISSUE TITLE
LUT file extension should be compared in case insensitive mode

### ISSUE THREAD

**Issue by jbebe** [lauralex/dwm_lut#3]
Relevant section:

https://github.com/lauralex/dwm_lut/blob/c7f36dc94e4350edd728ffc4c0163f9fb9f85f58/DwmLutGUI/DwmLutGUI/Injector.cs#L74-L80

I was just surprised that my xyz.CUBE file was invalid. It was uppercase everywhere I found lut files.

**Comment by lauralex** [comment]
> 

Yeah, gonna fix that
