### ISSUE TITLE
Windows 23H2 support?

### ISSUE THREAD

**Issue by ectv96** [lauralex/dwm_lut#33]
when i try to apply DWMLUTGUI on a laptop that runs on 23H2 (developer), it shows an error that LUT can't be applied due to incorrect LUT/DWM got updated.

**Comment by lauralex** [comment]
I'll have to reverse engineer the dwm again

**Comment by lauralex** [comment]
It requires a little bit of effort, so I'll do it when I have free time.

**Comment by lauralex** [comment]
Also, I'll have to download the Windows 11 23H2 image, if anyone has the will to reverse the dwm before, it'd be great!

**Comment by casef** [comment]
Will, yes. Skill...likely not...?

**Comment by Ruabc123** [comment]
any updates?

**Comment by markanini** [comment]
Works fine with the 23H2 here. If someone can verify this can be closed.

**Comment by winloud** [comment]
Works fine with the 23H2 until now, UI windows can't open.

**Comment by lauralex** [comment]
It works fine also for me
