### ISSUE TITLE
Windows 11 23H2 when exiting HDR back to SDR it loses all settings

### ISSUE THREAD

**Issue by mbze430** [lauralex/dwm_lut#42]
Not sure if this is a specific issue with Windows 11 23H2, but I only started using this app since 23H2.

On my Lenovo Legion 9i, if I set the LUT for SDR in SDR mode.  Works great.  When switching to HDR mode the GUI will say "(changed)" and then exiting out of HDR mode it will remove all the settings where the LUT is located.

**Comment by lauralex** [comment]
Solved by #48
