### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by LogicalSoIutions** [lauralex/dwm_lut#5]
Ability to add hotkey to apply/disable filters? Alt-Tabbing crashes a few of my friends game but we love what we can do with the filters from this. Nothing crazy needed, just one hotkey for each. 

Thanks

**Comment by t12lve** [comment]
yeah, maybe the ability to disable hdr line + like 3 lut pré defined :)

kiss @LogicalSoIutions  <3 love ur work

**Comment by lauralex** [comment]
Yes, it is a nice feature to have. I will add that!

**Comment by antonmeleshkevich** [comment]
Is there a chance to have a hotkey for switching from one LUT to another? For example, a hotkey to select next LUT in the folder. I have P3 capable display calibrated with LUTs created with DisplayCal. Most of the time I want my display to be gamma 2.4 rec709, but sometimes - gamma 2.6 P3-D65. Or sometimes BT.1886 to better see the shadows.
Maybe something like ctrl+alt+shift+1 for monitor 1, ctrl+alt+shift+2 for monitor 2 and so on, as the defaults, with the option to change the hotkeys per monitor.
But anyway, thanks again for the huge amount of work you've done to make it work on Windows 11!

**Comment by lauralex** [comment]
Yeah, good suggestion, but I think it's best to add slots in the GUI, so that you can select multiple LUTs per monitor, instead of searching them in a folder (which can lead to undefined behavior)

**Comment by lauralex** [comment]
You can check the development repo: https://github.com/lauralex/dwm_lut/tree/5-multi-lut-toggle. Toggle functionality must be implemented, but you should be able to use multiple LUTs per monitor using a dropdown menu

**Comment by lauralex** [comment]
I almost finished the toggle functionality. Right now, you can build the dev branch yourself and toggle LUTs using the NUMPAD 1 key on your keyboard
