### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by adolfotregosa** [lauralex/dwm_lut#54]
testing.txt lut from colorspace 3d eecolor65

![error](https://github.com/lauralex/dwm_lut/assets/7437931/867d32d8-2eba-4f94-bad0-28d487bef920)
[testing.txt](https://github.com/lauralex/dwm_lut/files/14733891/testing.txt)

Suggestions ??

**Comment by flakyferr** [comment]
I'm having the same problem. What version of windows are you on? I'm on Windows 11 24H2, version 26120.461 of the Dev insider program.
