### ISSUE TITLE
Failed to initialize...

### ISSUE THREAD

**Issue by tgiannet** [lauralex/dwm_lut#6]
I downloaded the latest version and followed the instructions. 
I ran the program as Admin, but I got an error on loading a LUT file to the SRT.

"Failed to load or initialize the DLL. This is probably because the LUT file is malformed or that DWM got updated."
![2023-02-10 16 21 21](https://user-images.githubusercontent.com/7050393/218199991-6adfd5b6-d739-4795-a801-9e4ff299a0cd.png)

Running Windows 11, NVidia GeForce RTX 4080, MSI Optix G27 Series Monitors

**Comment by ed-weird** [comment]
I'm seeing this issue as well, attempted with multiple .cube files to try it out.

**Comment by KlausFallz** [comment]
+1 to the pop up. Will try to re-download

**Comment by tgiannet** [comment]
yeah, looks like it's a WIN11 issue - there was another version of the 3.8 DWM that fixed it for me
