### ISSUE TITLE
Program seems to not work with Laptops

### ISSUE THREAD

**Issue by DarthSlane** [lauralex/dwm_lut#8]
This program does not seem to work with laptop monitors. I have tried to restart and redownload multiple times. I am trying to use the Escape from Tarkov filters and they do not apply at all. I am using a 2021 Lenovo Legion 5 pro.

**Comment by lauralex** [comment]
Strange, did you try with a desktop monitor?

**Comment by DarthSlane** [comment]
I do not own a desktop monitor currently.

**Comment by dr-mengyu** [comment]
> This program does not seem to work with laptop monitors. I have tried to restart and redownload multiple times. I am trying to use the Escape from Tarkov filters and they do not apply at all. I am using a 2021 Lenovo Legion 5 pro.

If you're using Windows 11 22H2 or later, check if "Automatically manage color for apps" is turned on in Start Memu > Settings > System > Display > Advanced display. 
I found that DwmLut doesn't take effect with this setting turned on. Just turning it off and DwmLut works great for me.

**Comment by DarthSlane** [comment]
Thank you very much it seems to work now. The only problem is that Escape from Tarkov has banned the use of the LUT. I hope the Programmer/s best of luck with future advances in their career/s and to dr-mengyu I hope you have a good day.
