### ISSUE TITLE
Does not wotk with disabled "Fullscreen optimisations"

### ISSUE THREAD

**Issue by DrParanoia** [lauralex/dwm_lut#9]
Not sure if this is even fixable. But if the game is in Fullscreen mode with "Fullscreen optimisations" disabled, the LUT has no effect on the game.

**Comment by lauralex** [comment]
> Not sure if this is even fixable. But if the game is in Fullscreen mode with "Fullscreen optimisations" disabled, the LUT has no effect on the game.

Not fixable, since fullscreen optimizations lets the DWM process apply an overlay to fullscreen applications. What "fullscreen optimizations" does is basically convert a fullscreen exclusive application into a "highly optimized" borderless windowed application, at runtime.

**Comment by DrParanoia** [comment]
Yep, figured that much while reading what "Fullscreen optimisation" does. Basically disabling it also disables the DWM, and this project is indeed called "DWM LUT" 😆
